baseURL = 'https://podcastatlas.ai/'
locale = 'en-us'
title = 'My New Hugo Project'
theme = 'hugo-xmin'
preview_urls = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[outputs]
page = ['html','markdown']
