#!/usr/bin/env python3
"""Generate stable On This Day route shells for every calendar date."""

from __future__ import annotations

import argparse
import calendar
import datetime as dt
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = Path("content/on-this-day")
GENERATED_NOTICE = (
    "<!-- Generated by scripts/prepare-on-this-day.py; do not edit manually. -->"
)


def _front_matter(values: dict[str, object]) -> str:
    lines = ["---"]
    for key, value in values.items():
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        else:
            rendered = json.dumps(value, ensure_ascii=False)
        lines.append(f"{key}: {rendered}")
    lines.extend(["---", GENERATED_NOTICE, ""])
    return "\n".join(lines)


def expected_pages() -> dict[Path, str]:
    pages = {
        Path("_index.md"): _front_matter(
            {
                "title": "On This Day",
                "type": "on-this-day",
                "description": "Browse podcast episodes published on this calendar date in previous years.",
            }
        )
    }
    for month in range(1, 13):
        for day in range(1, calendar.monthrange(2000, month)[1] + 1):
            month_day = f"{month:02d}-{day:02d}"
            label = f"{dt.date(2000, month, day).strftime('%B')} {day}"
            pages[Path(month_day) / "_index.md"] = _front_matter(
                {
                    "title": f"On This Day: {label}",
                    "type": "on-this-day",
                    "month_day": month_day,
                    "description": (
                        f"Podcast episodes from previous years for {label}, with nearby dates "
                        "shown when there is no exact match."
                    ),
                }
            )
    return pages


def safe_output_path(root: Path) -> Path:
    repository = root.resolve(strict=True)
    output = repository / OUTPUT_DIR
    resolved_output = output.resolve(strict=False)
    if not resolved_output.is_relative_to(repository):
        raise ValueError(
            f"Refusing to write On This Day projections outside repository: {output}"
        )

    current = repository
    for part in OUTPUT_DIR.parts:
        current /= part
        if current.is_symlink():
            raise ValueError(f"Refusing symlinked On This Day output path: {current}")
    return output


def _existing_files(output: Path) -> set[Path]:
    if output.is_symlink():
        raise ValueError(f"Generated output directory must not be a symlink: {output}")
    if not output.exists():
        return set()
    files: set[Path] = set()
    for path in output.rglob("*"):
        if path.is_symlink():
            raise ValueError(f"Generated output must not contain symlinks: {path}")
        if path.is_file():
            files.add(path.relative_to(output))
    return files


def generate(root: Path = ROOT, *, check: bool = False) -> list[Path]:
    output = safe_output_path(root)
    expected = expected_pages()
    existing = _existing_files(output)

    unexpected = sorted(existing - expected.keys())
    for relative in unexpected:
        path = output / relative
        if GENERATED_NOTICE not in path.read_text(encoding="utf-8"):
            raise ValueError(f"Refusing to remove unowned file from generated output: {path}")

    for relative in sorted(existing & expected.keys()):
        path = output / relative
        content = path.read_text(encoding="utf-8")
        if content != expected[relative] and GENERATED_NOTICE not in content:
            raise ValueError(f"Refusing to overwrite unowned file in generated output: {path}")

    changes: list[Path] = []
    for relative, content in expected.items():
        path = output / relative
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            changes.append(path)
    changes.extend(output / relative for relative in unexpected)

    if check:
        if changes:
            repository = root.resolve(strict=True)
            paths = ", ".join(str(path.relative_to(repository)) for path in changes[:5])
            suffix = "" if len(changes) <= 5 else f" and {len(changes) - 5} more"
            raise ValueError(f"On This Day projections are stale: {paths}{suffix}")
        return []

    if safe_output_path(root) != output or _existing_files(output) != existing:
        raise ValueError("Generated output changed during On This Day preparation")
    output.mkdir(parents=True, exist_ok=True)
    for relative in unexpected:
        (output / relative).unlink()
    for relative, content in expected.items():
        path = output / relative
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    for directory in sorted(
        (path for path in output.rglob("*") if path.is_dir()), reverse=True
    ):
        if not any(directory.iterdir()):
            directory.rmdir()
    return changes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        changes = generate(ROOT, check=args.check)
    except ValueError as error:
        parser.error(str(error))
    if args.check:
        print("On This Day projections are current.")
    else:
        print(f"Prepared {len(expected_pages())} On This Day route pages; changed {len(changes)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
