#!/usr/bin/env python3
"""Derive short public overview pages from the canonical overview and Git history."""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import hashlib
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parents[1]
CANONICAL_OVERVIEW = Path("content/wiki/overview.md")
PROJECTION_DIR = Path("content/wiki-projections")
# Normalize author timestamps to the content publisher's calendar day, independent of build-host TZ.
HISTORY_TIMEZONE = "Australia/Melbourne"
GENERATED_NOTICE = "<!-- Generated by scripts/prepare-overview-projections.py; do not edit manually. -->"
HEADING_PATTERNS = {
    "overview": re.compile(r"(?m)^# Overview\s*$"),
    "current_synthesis": re.compile(r"(?m)^## Current Synthesis\s*$"),
    "open_questions": re.compile(r"(?m)^## Open Questions\s*$"),
}
STATUS_PREFIX_RE = re.compile(
    r"^(?:The|A|An)\s+(?:latest|newest|previous|earlier|recent)\s+",
    re.IGNORECASE,
)


@dataclass(frozen=True)
class OverviewSections:
    update_history: str
    current_synthesis: str
    open_questions: str


@dataclass(frozen=True)
class UpdateEvent:
    commit: str
    markdown: str


@dataclass(frozen=True)
class OverviewRevision:
    commit: str
    authored_at: dt.datetime
    old_blob: str
    new_blob: str


def run_git(repo: Path, *args: str, input_text: str | None = None) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=True,
            text=True,
            input=input_text,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except subprocess.CalledProcessError as error:
        detail = error.stderr.strip() or error.stdout.strip() or str(error)
        raise RuntimeError(f"Git command failed: {detail}") from error
    return result.stdout


def split_overview_sections(text: str) -> OverviewSections:
    matches = {name: list(pattern.finditer(text)) for name, pattern in HEADING_PATTERNS.items()}
    for name, values in matches.items():
        if len(values) != 1:
            heading = name.replace("_", " ").title()
            raise ValueError(f"Overview must contain exactly one {heading} heading; found {len(values)}")

    overview_heading = matches["overview"][0]
    synthesis_heading = matches["current_synthesis"][0]
    questions_heading = matches["open_questions"][0]
    if not (overview_heading.end() < synthesis_heading.start() < questions_heading.start()):
        raise ValueError("Overview headings are out of order")

    return OverviewSections(
        update_history=text[overview_heading.end() : synthesis_heading.start()].strip(),
        current_synthesis=text[synthesis_heading.end() : questions_heading.start()].strip(),
        open_questions=text[questions_heading.end() :].strip(),
    )


def markdown_paragraphs(text: str) -> list[str]:
    return [paragraph.strip() for paragraph in re.split(r"\n\s*\n", text.strip()) if paragraph.strip()]


def normalized_update(paragraph: str) -> str:
    return STATUS_PREFIX_RE.sub("The STATUS ", paragraph, count=1)


def is_aggregate_summary(paragraph: str) -> bool:
    stripped = paragraph.strip("*_ ")
    return stripped.startswith("The wiki currently tracks ") or stripped.startswith(
        "This page is maintained by the LLM. It is updated on every ingest"
    )


def changed_update_paragraphs(parent: list[str], child: list[str]) -> list[str]:
    """Return child paragraphs not present in the parent after status-word normalization."""
    available = collections.Counter(normalized_update(paragraph) for paragraph in parent)
    changed: list[str] = []
    for paragraph in child:
        normalized = normalized_update(paragraph)
        if available[normalized]:
            available[normalized] -= 1
        elif not is_aggregate_summary(paragraph):
            changed.append(paragraph)
    return changed


def overview_revisions(repo: Path, canonical_path: Path) -> list[OverviewRevision]:
    output = run_git(
        repo,
        "log",
        "--reverse",
        "--format=@@@%H%x09%aI",
        "--raw",
        "--no-abbrev",
        "--no-renames",
        "--",
        canonical_path.as_posix(),
    )
    revisions: list[OverviewRevision] = []
    pending: tuple[str, dt.datetime] | None = None
    for line in output.splitlines():
        if line.startswith("@@@"):
            commit, authored_at = line[3:].split("\t", 1)
            pending = (commit, dt.datetime.fromisoformat(authored_at))
            continue
        if not line.startswith(":") or pending is None:
            continue
        metadata, changed_path = line.split("\t", 1)
        if changed_path != canonical_path.as_posix():
            continue
        fields = metadata.split()
        if len(fields) < 5:
            raise RuntimeError(f"Cannot parse Git raw history for {pending[0]}")
        revisions.append(
            OverviewRevision(
                commit=pending[0],
                authored_at=pending[1],
                old_blob=fields[2],
                new_blob=fields[3],
            )
        )
        pending = None
    if not revisions:
        raise RuntimeError(f"No Git history found for {canonical_path}")
    return revisions


class GitBlobReader:
    def __init__(self, repo: Path):
        self.process = subprocess.Popen(
            ["git", "-C", str(repo), "cat-file", "--batch"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

    def read(self, object_id: str) -> str:
        if set(object_id) == {"0"}:
            return ""
        assert self.process.stdin is not None and self.process.stdout is not None
        self.process.stdin.write(f"{object_id}\n".encode("ascii"))
        self.process.stdin.flush()
        header = self.process.stdout.readline().decode("ascii", errors="replace").strip().split()
        if len(header) != 3 or header[1] != "blob":
            raise RuntimeError(f"Cannot read overview blob {object_id}: {' '.join(header)}")
        size = int(header[2])
        content = self.process.stdout.read(size)
        terminator = self.process.stdout.read(1)
        if terminator != b"\n":
            raise RuntimeError(f"Invalid Git batch response for {object_id}")
        return content.decode("utf-8")

    def close(self) -> None:
        if self.process.stdin:
            self.process.stdin.close()
        return_code = self.process.wait()
        stderr = self.process.stderr.read().decode("utf-8", errors="replace") if self.process.stderr else ""
        if self.process.stdout:
            self.process.stdout.close()
        if self.process.stderr:
            self.process.stderr.close()
        if return_code:
            raise RuntimeError(f"git cat-file failed: {stderr.strip()}")

    def __enter__(self) -> "GitBlobReader":
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        if exc_type is not None:
            self.process.kill()
            self.process.wait()
            return
        self.close()


def require_full_history(repo: Path) -> None:
    shallow = run_git(repo, "rev-parse", "--is-shallow-repository").strip()
    if shallow == "true":
        raise RuntimeError("Overview projections require full Git history; shallow repositories are rejected")


def collect_update_history(
    repo: Path,
    canonical_path: Path = CANONICAL_OVERVIEW,
    timezone_name: str = HISTORY_TIMEZONE,
) -> dict[str, list[UpdateEvent]]:
    require_full_history(repo)
    timezone = ZoneInfo(timezone_name)
    revisions = overview_revisions(repo, canonical_path)
    grouped: dict[str, list[UpdateEvent]] = collections.defaultdict(list)
    previous_blob = ""
    previous_paragraphs: list[str] = []

    with GitBlobReader(repo) as blobs:
        for revision in revisions:
            if revision.old_blob == previous_blob:
                parent_paragraphs = previous_paragraphs
            elif set(revision.old_blob) == {"0"}:
                parent_paragraphs = []
            else:
                parent_text = blobs.read(revision.old_blob)
                parent_paragraphs = markdown_paragraphs(split_overview_sections(parent_text).update_history)

            child_text = blobs.read(revision.new_blob)
            child_paragraphs = markdown_paragraphs(split_overview_sections(child_text).update_history)
            updates = changed_update_paragraphs(parent_paragraphs, child_paragraphs)
            if updates:
                day = revision.authored_at.astimezone(timezone).date().isoformat()
                grouped[day].extend(UpdateEvent(revision.commit, paragraph) for paragraph in updates)

            previous_blob = revision.new_blob
            previous_paragraphs = child_paragraphs

    return {day: grouped[day] for day in sorted(grouped, reverse=True)}


def front_matter(title: str, url: str, *, commits: list[str] | None = None) -> list[str]:
    lines = [
        "---",
        f'title: "{title}"',
        'type: "wiki"',
        f'url: "{url}"',
        'outputs: ["html"]',
        "wiki_projection: true",
    ]
    if commits:
        lines.append("update_commits:")
        lines.extend(f'  - "{commit}"' for commit in commits)
    lines.extend(["---", "", GENERATED_NOTICE, ""])
    return lines


def overview_page(sections: OverviewSections) -> str:
    lines = front_matter("Overview", "/wiki/overview/")
    lines.extend(
        [
            "# Overview",
            "",
            "## Update History",
            "",
            "[Browse updates grouped by day](../update-history/).",
            "",
            "## Open Questions",
            "",
            "[View all current unanswered questions](../open-questions/).",
            "",
            "## Current Synthesis",
            "",
            sections.current_synthesis,
            "",
        ]
    )
    return "\n".join(lines)


def open_questions_page(sections: OverviewSections) -> str:
    lines = front_matter("Open Questions", "/wiki/open-questions/")
    lines.extend(["# Open Questions", "", sections.open_questions, ""])
    return "\n".join(lines)


def update_history_index(history: dict[str, list[UpdateEvent]]) -> str:
    lines = front_matter("Update History", "/wiki/update-history/")
    lines.extend(["# Update History", ""])
    for day in history:
        lines.append(f"- [{day}]({day}/)")
    lines.append("")
    return "\n".join(lines)


def daily_update_page(day: str, events: list[UpdateEvent]) -> str:
    commits = list(dict.fromkeys(event.commit for event in events))
    lines = front_matter(day, f"/wiki/update-history/{day}/", commits=commits)
    lines.extend([f"# {day}", ""])
    for index, event in enumerate(events):
        if index:
            lines.extend(["---", ""])
        lines.extend([f"<!-- commit: {event.commit} -->", "", event.markdown, ""])
    return "\n".join(lines)


def expected_projection_files(
    root: Path,
    sections: OverviewSections,
    history: dict[str, list[UpdateEvent]],
) -> dict[Path, str]:
    output = root / PROJECTION_DIR
    expected = {
        output / "overview" / "index.md": overview_page(sections),
        output / "open-questions" / "index.md": open_questions_page(sections),
        output / "update-history" / "_index.md": update_history_index(history),
    }
    for day, events in history.items():
        if events:
            expected[output / "update-history" / day / "index.md"] = daily_update_page(day, events)
    return expected


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_projection_files(root: Path, expected: dict[Path, str]) -> list[Path]:
    root = root.resolve()
    output_path = root / PROJECTION_DIR
    if output_path.is_symlink():
        raise RuntimeError(f"Refusing to use a symlinked generated directory: {output_path}")
    output = output_path.resolve()
    if root not in output.parents:
        raise RuntimeError("Overview generated directory escaped the repository")
    expected_resolved = {path.resolve(): content for path, content in expected.items()}
    if any(output not in path.parents for path in expected_resolved):
        raise RuntimeError("Overview projection path escaped its generated directory")

    changed: list[Path] = []
    if output.exists():
        for path in sorted(output.rglob("*.md")):
            resolved = path.resolve()
            if resolved in expected_resolved:
                continue
            if GENERATED_NOTICE not in path.read_text(encoding="utf-8"):
                raise RuntimeError(f"Refusing to delete unmarked projection file: {path}")
            path.unlink()
            changed.append(path)

    for path, content in expected_resolved.items():
        if write_if_changed(path, content):
            changed.append(path)

    if output.exists():
        for directory in sorted((path for path in output.rglob("*") if path.is_dir()), reverse=True):
            try:
                directory.rmdir()
            except OSError:
                pass
    return changed


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(root: Path) -> int:
    canonical = root / CANONICAL_OVERVIEW
    if not canonical.exists():
        print(f"Missing canonical overview: {canonical}", file=sys.stderr)
        return 1
    before = sha256(canonical)
    try:
        sections = split_overview_sections(canonical.read_text(encoding="utf-8"))
        history = collect_update_history(root)
        expected = expected_projection_files(root, sections, history)
        changed = sync_projection_files(root, expected)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Overview projection failed: {error}", file=sys.stderr)
        return 1
    after = sha256(canonical)
    if before != after:
        print("Overview projection modified the canonical overview", file=sys.stderr)
        return 1
    print(
        f"Overview projections: days={len(history)}, "
        f"updates={sum(len(events) for events in history.values())}, "
        f"open_questions={'present' if sections.open_questions else 'empty'}, "
        f"changed_files={len(changed)}"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    return run(args.root.resolve())


if __name__ == "__main__":
    raise SystemExit(main())
