#!/usr/bin/env python3
"""Derive public synthesis, history, and question pages from the canonical overview."""

from __future__ import annotations

import argparse
import collections
import datetime as dt
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parents[1]
CANONICAL_OVERVIEW = Path("content/wiki/overview.md")
PROJECTION_DIR = Path("content/wiki-projections")
COMPACT_SYNTHESIS = Path("content/wiki/_generated/synthesis/current.md")
COMPACT_MANIFEST = Path("content/wiki/_generated/synthesis/manifest.json")
COMPACT_GENERATED_PREFIX = "<!-- Generated by tools.synthesis;"
# Normalize author timestamps to the content publisher's calendar day, independent of build-host TZ.
HISTORY_TIMEZONE = "Australia/Melbourne"
GENERATED_NOTICE = "<!-- Generated by scripts/prepare-overview-projections.py; do not edit manually. -->"
HEADING_PATTERNS = {
    "overview": re.compile(r"(?m)^# Overview\s*$"),
    "current_synthesis": re.compile(r"(?m)^## Current Synthesis\s*$"),
    "open_questions": re.compile(r"(?m)^## Open Questions\s*$"),
}
STATUS_PREFIX_RE = re.compile(
    r"^(?:The|A|An)\s+(?:latest|newest|previous|earlier|recent)\s+",
    re.IGNORECASE,
)
WIKI_LINK_TARGET_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")


@dataclass(frozen=True)
class OverviewSections:
    update_history: str
    current_synthesis: str
    open_questions: str


@dataclass(frozen=True)
class CurrentSynthesisSource:
    body: str
    summary: str = ""
    last_updated: str = ""
    as_of_overview_commit: str = ""
    synthesis_source: str = "overview-legacy"
    episode_count: int | None = None
    source_count: int | None = None
    topic_count: int | None = None


@dataclass(frozen=True)
class UpdateEvent:
    commit: str
    markdown: str


@dataclass(frozen=True)
class OverviewRevision:
    commit: str
    authored_at: dt.datetime
    old_blob: str
    new_blob: str


def run_git(repo: Path, *args: str, input_text: str | None = None) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(repo), *args],
            check=True,
            text=True,
            input=input_text,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
    except subprocess.CalledProcessError as error:
        detail = error.stderr.strip() or error.stdout.strip() or str(error)
        raise RuntimeError(f"Git command failed: {detail}") from error
    return result.stdout


def split_overview_sections(text: str) -> OverviewSections:
    matches = {name: list(pattern.finditer(text)) for name, pattern in HEADING_PATTERNS.items()}
    for name, values in matches.items():
        if len(values) != 1:
            heading = name.replace("_", " ").title()
            raise ValueError(f"Overview must contain exactly one {heading} heading; found {len(values)}")

    overview_heading = matches["overview"][0]
    synthesis_heading = matches["current_synthesis"][0]
    questions_heading = matches["open_questions"][0]
    if not (overview_heading.end() < synthesis_heading.start() < questions_heading.start()):
        raise ValueError("Overview headings are out of order")

    return OverviewSections(
        update_history=text[overview_heading.end() : synthesis_heading.start()].strip(),
        current_synthesis=text[synthesis_heading.end() : questions_heading.start()].strip(),
        open_questions=text[questions_heading.end() :].strip(),
    )


def markdown_paragraphs(text: str) -> list[str]:
    return [paragraph.strip() for paragraph in re.split(r"\n\s*\n", text.strip()) if paragraph.strip()]


def _strip_scalar(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        try:
            parsed = json.loads(value)
        except json.JSONDecodeError as error:
            raise ValueError("Invalid quoted compact synthesis metadata") from error
        if not isinstance(parsed, str):
            raise ValueError("Compact synthesis metadata scalar must be a string")
        return parsed
    if len(value) >= 2 and value[0] == value[-1] == "'":
        return value[1:-1]
    return value


def _require_regular_repo_file(root: Path, path: Path, label: str) -> None:
    resolved_root = root.resolve()
    lexical_path = path.parent.resolve() / path.name
    try:
        relative = lexical_path.relative_to(resolved_root)
    except ValueError as error:
        raise ValueError(f"{label} escapes the repository") from error
    current = resolved_root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"{label} must not be a symbolic link")
    if not path.is_file():
        raise ValueError(f"{label} is missing")


def _digest_json(value: object) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _load_compact_files(
    root: Path,
    sections: OverviewSections,
    path: Path,
    manifest_path: Path,
    *,
    artifact_root: Path | None = None,
) -> CurrentSynthesisSource:
    artifact_root = artifact_root or root
    if path.is_symlink():
        raise ValueError("Compact synthesis current.md must not be a symbolic link")
    if manifest_path.is_symlink():
        raise ValueError("Compact synthesis manifest must not be a symbolic link")
    if not path.is_file():
        raise ValueError("Existing generated compact synthesis is missing current.md")
    if not manifest_path.is_file():
        raise ValueError("Existing generated compact synthesis is missing its manifest")
    _require_regular_repo_file(artifact_root, path, "Compact synthesis current.md")
    _require_regular_repo_file(artifact_root, manifest_path, "Compact synthesis manifest")
    text = path.read_text(encoding="utf-8")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError("Existing generated compact synthesis has an invalid manifest") from error
    if not isinstance(manifest, dict) or manifest.get("schema_version") != 1 or manifest.get("generated") is not True:
        raise ValueError("Existing generated compact synthesis has an unsupported manifest")
    global_state = manifest.get("global")
    if not isinstance(global_state, dict) or global_state.get("output_digest") != hashlib.sha256(text.encode("utf-8")).hexdigest():
        raise ValueError("Existing generated compact synthesis digest differs from its manifest")

    lines = text.splitlines()
    if not lines or not lines[0].startswith(COMPACT_GENERATED_PREFIX):
        raise ValueError("Existing generated compact synthesis is missing its generated marker")
    try:
        front_start = lines.index("---", 1)
        front_end = lines.index("---", front_start + 1)
    except ValueError as error:
        raise ValueError("Existing generated compact synthesis has invalid front matter") from error

    metadata: dict[str, str] = {}
    for raw_line in lines[front_start + 1 : front_end]:
        if ":" not in raw_line:
            continue
        key, value = raw_line.split(":", 1)
        metadata[key.strip()] = _strip_scalar(value)
    required = (
        "schema_version", "generated", "synthesis_source", "last_updated",
        "as_of_overview_commit", "summary", "episode_count", "source_count", "topic_count",
    )
    if any(not metadata.get(key) for key in required):
        raise ValueError("Existing generated compact synthesis is missing required metadata")
    if metadata["schema_version"] != "1" or metadata["generated"].lower() != "true" or metadata["synthesis_source"] != "compact":
        raise ValueError("Existing generated compact synthesis has unsupported metadata")
    try:
        dt.date.fromisoformat(metadata["last_updated"])
    except ValueError as error:
        raise ValueError("Existing generated compact synthesis has an invalid last_updated date") from error
    counts: dict[str, int] = {}
    for key in ("episode_count", "source_count", "topic_count"):
        if not re.fullmatch(r"0|[1-9][0-9]*", metadata[key]):
            raise ValueError(f"Existing generated compact synthesis has an invalid {key}")
        counts[key] = int(metadata[key])
    corpus = global_state.get("corpus")
    if not isinstance(corpus, dict) or any(corpus.get(key) != counts[key] for key in ("episode_count", "source_count")):
        raise ValueError("Existing generated compact synthesis corpus differs from its manifest")
    if global_state.get("overview_commit") != metadata["as_of_overview_commit"]:
        raise ValueError("Existing generated compact synthesis commit differs from its manifest")
    if global_state.get("content_date") != metadata["last_updated"]:
        raise ValueError("Existing generated compact synthesis date differs from its manifest")
    topics = manifest.get("topics")
    if not isinstance(topics, dict) or len(topics) != counts["topic_count"]:
        raise ValueError("Existing generated compact synthesis topic count differs from its manifest")
    base = path.parent
    topic_ids = set(topics)
    topic_files = {candidate.stem for candidate in (base / "topics").glob("*.md")}
    claim_files = {candidate.stem for candidate in (base / "claims").glob("*.json")}
    if topic_files != topic_ids or claim_files != topic_ids:
        raise ValueError("Existing generated compact synthesis topic components are incomplete")
    for topic_id, state in topics.items():
        if not isinstance(state, dict):
            raise ValueError(f"Existing generated compact synthesis topic {topic_id} has invalid state")
        topic_path = base / "topics" / f"{topic_id}.md"
        claims_path = base / "claims" / f"{topic_id}.json"
        _require_regular_repo_file(artifact_root, topic_path, f"Compact topic {topic_id}")
        _require_regular_repo_file(artifact_root, claims_path, f"Compact claims {topic_id}")
        topic_digest = hashlib.sha256(topic_path.read_bytes()).hexdigest()
        if topic_digest != state.get("output_digest"):
            raise ValueError(f"Existing generated compact synthesis topic {topic_id} digest differs")
        try:
            claim_payload = json.loads(claims_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            raise ValueError(f"Existing generated compact synthesis claims {topic_id} are invalid") from error
        if _digest_json(claim_payload) != state.get("claim_digest"):
            raise ValueError(f"Existing generated compact synthesis claims {topic_id} digest differs")
    ledger_path = base / "paragraph-ledger.json"
    _require_regular_repo_file(artifact_root, ledger_path, "Compact synthesis paragraph ledger")
    try:
        ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise ValueError("Existing generated compact synthesis paragraph ledger is invalid") from error
    paragraphs = ledger.get("paragraphs") if isinstance(ledger, dict) else None
    coverage = ledger.get("coverage") if isinstance(ledger, dict) else None
    if (
        not isinstance(paragraphs, list)
        or not isinstance(coverage, dict)
        or len(paragraphs) != manifest.get("paragraph_count")
        or coverage.get("paragraph_count") != len(paragraphs)
        or ledger.get("overview_digest") != manifest.get("overview_digest")
    ):
        raise ValueError("Existing generated compact synthesis paragraph ledger differs from its manifest")

    body = "\n".join(lines[front_end + 1 :]).strip()
    if len(re.findall(r"(?m)^# Current Synthesis\s*$", body)) != 1:
        raise ValueError("Existing generated compact synthesis must have one Current Synthesis heading")
    body = re.sub(r"(?m)^# Current Synthesis\s*\n+", "", body, count=1).strip()
    for heading in ("Executive Summary", "Synthesis by Domain"):
        if len(re.findall(rf"(?m)^## {re.escape(heading)}\s*$", body)) != 1:
            raise ValueError(f"Existing generated compact synthesis must have one {heading} heading")
    wiki_root = root / "content" / "wiki"
    known_targets = {
        candidate.stem
        for section in ("concepts", "entities", "sources")
        for candidate in (wiki_root / section).glob("*.md")
        if not candidate.name.startswith("_")
    }
    broken_targets = sorted(set(WIKI_LINK_TARGET_RE.findall(body)) - known_targets)
    if broken_targets:
        raise ValueError(
            "Existing generated compact synthesis has missing Wiki targets: "
            + ", ".join(broken_targets[:10])
        )
    return CurrentSynthesisSource(
        body=body,
        summary=metadata["summary"],
        last_updated=metadata["last_updated"],
        as_of_overview_commit=metadata["as_of_overview_commit"],
        synthesis_source="compact",
        episode_count=counts["episode_count"],
        source_count=counts["source_count"],
        topic_count=counts["topic_count"],
    )


def _git_show_optional(repo: Path, revision: str, path: Path) -> str | None:
    result = subprocess.run(
        ["git", "-C", str(repo), "show", f"{revision}:{path.as_posix()}"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return result.stdout if result.returncode == 0 else None


def _historical_compact_synthesis(
    root: Path, sections: OverviewSections
) -> CurrentSynthesisSource | None:
    result = subprocess.run(
        [
            "git", "-C", str(root), "log", "--format=%H", "--",
            COMPACT_SYNTHESIS.as_posix(), COMPACT_MANIFEST.as_posix(),
        ],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if result.returncode != 0:
        return None
    for commit in (line.strip() for line in result.stdout.splitlines() if line.strip()):
        current_text = _git_show_optional(root, commit, COMPACT_SYNTHESIS)
        manifest_text = _git_show_optional(root, commit, COMPACT_MANIFEST)
        if current_text is None or manifest_text is None:
            continue
        try:
            manifest = json.loads(manifest_text)
        except json.JSONDecodeError:
            continue
        topics = manifest.get("topics") if isinstance(manifest, dict) else None
        if not isinstance(topics, dict):
            continue
        relative_files = [
            COMPACT_SYNTHESIS,
            COMPACT_MANIFEST,
            COMPACT_SYNTHESIS.parent / "paragraph-ledger.json",
            *[COMPACT_SYNTHESIS.parent / "topics" / f"{topic_id}.md" for topic_id in topics],
            *[COMPACT_SYNTHESIS.parent / "claims" / f"{topic_id}.json" for topic_id in topics],
        ]
        with tempfile.TemporaryDirectory() as temp_dir:
            artifact_root = Path(temp_dir)
            complete = True
            for relative in relative_files:
                mode = subprocess.run(
                    ["git", "-C", str(root), "ls-tree", commit, "--", relative.as_posix()],
                    text=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                if mode.returncode != 0 or not mode.stdout.strip() or mode.stdout.startswith("120000 "):
                    complete = False
                    break
                content = _git_show_optional(root, commit, relative)
                if content is None:
                    complete = False
                    break
                destination = artifact_root / relative
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_text(content, encoding="utf-8")
            if not complete:
                continue
            try:
                return _load_compact_files(
                    root,
                    sections,
                    artifact_root / COMPACT_SYNTHESIS,
                    artifact_root / COMPACT_MANIFEST,
                    artifact_root=artifact_root,
                )
            except (OSError, ValueError):
                continue
    return None


def _legacy_metadata(root: Path, sections: OverviewSections) -> tuple[str, str]:
    paragraphs = markdown_paragraphs(sections.current_synthesis)
    if paragraphs:
        summary = WIKI_LINK_TARGET_RE.sub(lambda match: match.group(1), paragraphs[0])
        summary = re.sub(r"\s+", " ", summary).replace("\x00", "").strip()[:240]
    else:
        summary = ""
    result = subprocess.run(
        ["git", "-C", str(root), "log", "--format=%H%x09%aI", "--", CANONICAL_OVERVIEW.as_posix()],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    content_date = ""
    if result.returncode == 0:
        for line in result.stdout.splitlines():
            if "\t" not in line:
                continue
            commit, authored_at = line.split("\t", 1)
            text = _git_show_optional(root, commit, CANONICAL_OVERVIEW)
            if text is None:
                continue
            try:
                revision = split_overview_sections(text)
            except ValueError:
                continue
            if revision.current_synthesis != sections.current_synthesis:
                break
            content_date = dt.datetime.fromisoformat(authored_at).astimezone(
                ZoneInfo(HISTORY_TIMEZONE)
            ).date().isoformat()
    return summary, content_date


def load_current_synthesis(root: Path, sections: OverviewSections) -> CurrentSynthesisSource:
    path = root / COMPACT_SYNTHESIS
    manifest_path = root / COMPACT_MANIFEST
    current_error: ValueError | None = None
    if path.exists() or manifest_path.exists() or path.is_symlink() or manifest_path.is_symlink():
        try:
            return _load_compact_files(root, sections, path, manifest_path)
        except ValueError as error:
            current_error = error

    historical = _historical_compact_synthesis(root, sections)
    if historical is not None:
        return historical
    if current_error is not None:
        raise current_error

    summary, content_date = _legacy_metadata(root, sections)
    return CurrentSynthesisSource(
        body=sections.current_synthesis,
        summary=summary,
        last_updated=content_date,
        synthesis_source="overview-legacy",
    )


def normalized_update(paragraph: str) -> str:
    return STATUS_PREFIX_RE.sub("The STATUS ", paragraph, count=1)


def is_aggregate_summary(paragraph: str) -> bool:
    stripped = paragraph.strip("*_ ")
    return stripped.startswith("The wiki currently tracks ") or stripped.startswith(
        "This page is maintained by the LLM. It is updated on every ingest"
    )


def changed_update_paragraphs(parent: list[str], child: list[str]) -> list[str]:
    """Return child paragraphs not present in the parent after status-word normalization."""
    available = collections.Counter(normalized_update(paragraph) for paragraph in parent)
    changed: list[str] = []
    for paragraph in child:
        normalized = normalized_update(paragraph)
        if available[normalized]:
            available[normalized] -= 1
        elif not is_aggregate_summary(paragraph):
            changed.append(paragraph)
    return changed


def overview_revisions(repo: Path, canonical_path: Path) -> list[OverviewRevision]:
    output = run_git(
        repo,
        "log",
        "--reverse",
        "--format=@@@%H%x09%aI",
        "--raw",
        "--no-abbrev",
        "--no-renames",
        "--",
        canonical_path.as_posix(),
    )
    revisions: list[OverviewRevision] = []
    pending: tuple[str, dt.datetime] | None = None
    for line in output.splitlines():
        if line.startswith("@@@"):
            commit, authored_at = line[3:].split("\t", 1)
            pending = (commit, dt.datetime.fromisoformat(authored_at))
            continue
        if not line.startswith(":") or pending is None:
            continue
        metadata, changed_path = line.split("\t", 1)
        if changed_path != canonical_path.as_posix():
            continue
        fields = metadata.split()
        if len(fields) < 5:
            raise RuntimeError(f"Cannot parse Git raw history for {pending[0]}")
        revisions.append(
            OverviewRevision(
                commit=pending[0],
                authored_at=pending[1],
                old_blob=fields[2],
                new_blob=fields[3],
            )
        )
        pending = None
    if not revisions:
        raise RuntimeError(f"No Git history found for {canonical_path}")
    return revisions


class GitBlobReader:
    def __init__(self, repo: Path):
        self.process = subprocess.Popen(
            ["git", "-C", str(repo), "cat-file", "--batch"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )

    def read(self, object_id: str) -> str:
        if set(object_id) == {"0"}:
            return ""
        assert self.process.stdin is not None and self.process.stdout is not None
        self.process.stdin.write(f"{object_id}\n".encode("ascii"))
        self.process.stdin.flush()
        header = self.process.stdout.readline().decode("ascii", errors="replace").strip().split()
        if len(header) != 3 or header[1] != "blob":
            raise RuntimeError(f"Cannot read overview blob {object_id}: {' '.join(header)}")
        size = int(header[2])
        content = self.process.stdout.read(size)
        terminator = self.process.stdout.read(1)
        if terminator != b"\n":
            raise RuntimeError(f"Invalid Git batch response for {object_id}")
        return content.decode("utf-8")

    def close(self) -> None:
        if self.process.stdin:
            self.process.stdin.close()
        return_code = self.process.wait()
        stderr = self.process.stderr.read().decode("utf-8", errors="replace") if self.process.stderr else ""
        if self.process.stdout:
            self.process.stdout.close()
        if self.process.stderr:
            self.process.stderr.close()
        if return_code:
            raise RuntimeError(f"git cat-file failed: {stderr.strip()}")

    def __enter__(self) -> "GitBlobReader":
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        if exc_type is not None:
            self.process.kill()
            self.process.wait()
            return
        self.close()


def require_full_history(repo: Path) -> None:
    shallow = run_git(repo, "rev-parse", "--is-shallow-repository").strip()
    if shallow == "true":
        raise RuntimeError("Overview projections require full Git history; shallow repositories are rejected")


def collect_update_history(
    repo: Path,
    canonical_path: Path = CANONICAL_OVERVIEW,
    timezone_name: str = HISTORY_TIMEZONE,
) -> dict[str, list[UpdateEvent]]:
    require_full_history(repo)
    timezone = ZoneInfo(timezone_name)
    revisions = overview_revisions(repo, canonical_path)
    grouped: dict[str, list[UpdateEvent]] = collections.defaultdict(list)
    previous_blob = ""
    previous_paragraphs: list[str] = []

    with GitBlobReader(repo) as blobs:
        for revision in revisions:
            if revision.old_blob == previous_blob:
                parent_paragraphs = previous_paragraphs
            elif set(revision.old_blob) == {"0"}:
                parent_paragraphs = []
            else:
                parent_text = blobs.read(revision.old_blob)
                parent_paragraphs = markdown_paragraphs(split_overview_sections(parent_text).update_history)

            child_text = blobs.read(revision.new_blob)
            child_paragraphs = markdown_paragraphs(split_overview_sections(child_text).update_history)
            updates = changed_update_paragraphs(parent_paragraphs, child_paragraphs)
            if updates:
                day = revision.authored_at.astimezone(timezone).date().isoformat()
                grouped[day].extend(UpdateEvent(revision.commit, paragraph) for paragraph in updates)

            previous_blob = revision.new_blob
            previous_paragraphs = child_paragraphs

    return {day: grouped[day] for day in sorted(grouped, reverse=True)}


def front_matter(
    title: str,
    url: str,
    *,
    aliases: list[str] | None = None,
    commits: list[str] | None = None,
) -> list[str]:
    lines = [
        "---",
        f'title: "{title}"',
        'type: "wiki"',
        f'url: "{url}"',
        'outputs: ["html"]',
        "wiki_projection: true",
    ]
    if aliases:
        lines.append("aliases:")
        lines.extend(f'  - "{alias}"' for alias in aliases)
    if commits:
        lines.append("update_commits:")
        lines.extend(f'  - "{commit}"' for commit in commits)
    lines.extend(["---", "", GENERATED_NOTICE, ""])
    return lines


def current_synthesis_page(source: CurrentSynthesisSource) -> str:
    lines = front_matter(
        "Current Synthesis",
        "/wiki/current-synthesis/",
        aliases=["/wiki/overview/"],
    )
    metadata: list[str] = [f"synthesis_source: {json.dumps(source.synthesis_source)}"]
    if source.summary:
        metadata.append(f"summary: {json.dumps(source.summary, ensure_ascii=False)}")
        metadata.append(f"description: {json.dumps(source.summary, ensure_ascii=False)}")
    if source.last_updated:
        metadata.append(f"last_updated: {json.dumps(source.last_updated)}")
    if source.as_of_overview_commit:
        metadata.append(f"as_of_overview_commit: {json.dumps(source.as_of_overview_commit)}")
    for key in ("episode_count", "source_count", "topic_count"):
        value = getattr(source, key)
        if value is not None:
            metadata.append(f"{key}: {value}")
    if metadata:
        marker = lines.index("---", 1)
        lines[marker:marker] = metadata
    lines.extend(["# Current Synthesis", ""])
    if source.last_updated:
        updated = dt.date.fromisoformat(source.last_updated)
        display_date = f"{updated.strftime('%B')} {updated.day}, {updated.year}"
        lines.extend(
            [
                f'<p class="synthesis-updated">Updated <time datetime="{source.last_updated}">{display_date}</time></p>',
                "",
            ]
        )
    lines.extend([source.body, ""])
    return "\n".join(lines)


def open_questions_page(sections: OverviewSections) -> str:
    lines = front_matter("Open Questions", "/wiki/open-questions/")
    lines.extend(["# Open Questions", "", sections.open_questions, ""])
    return "\n".join(lines)


def update_history_index(history: dict[str, list[UpdateEvent]]) -> str:
    lines = front_matter("Update History", "/wiki/update-history/")
    lines.extend(["# Update History", ""])
    for day in history:
        lines.append(f"- [{day}]({day}/)")
    lines.append("")
    return "\n".join(lines)


def daily_update_page(day: str, events: list[UpdateEvent]) -> str:
    commits = list(dict.fromkeys(event.commit for event in events))
    lines = front_matter(day, f"/wiki/update-history/{day}/", commits=commits)
    lines.extend([f"# {day}", ""])
    for index, event in enumerate(events):
        if index:
            lines.extend(["---", ""])
        lines.extend([f"<!-- commit: {event.commit} -->", "", event.markdown, ""])
    return "\n".join(lines)


def expected_projection_files(
    root: Path,
    sections: OverviewSections,
    history: dict[str, list[UpdateEvent]],
) -> dict[Path, str]:
    output = root / PROJECTION_DIR
    synthesis = load_current_synthesis(root, sections)
    expected = {
        output / "current-synthesis" / "index.md": current_synthesis_page(synthesis),
        output / "open-questions" / "index.md": open_questions_page(sections),
        output / "update-history" / "_index.md": update_history_index(history),
    }
    for day, events in history.items():
        if events:
            expected[output / "update-history" / day / "index.md"] = daily_update_page(day, events)
    return expected


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def sync_projection_files(root: Path, expected: dict[Path, str]) -> list[Path]:
    root = root.resolve()
    output_path = root / PROJECTION_DIR
    if output_path.is_symlink():
        raise RuntimeError(f"Refusing to use a symlinked generated directory: {output_path}")
    output = output_path.resolve()
    if root not in output.parents:
        raise RuntimeError("Overview generated directory escaped the repository")
    expected_resolved = {path.resolve(): content for path, content in expected.items()}
    if any(output not in path.parents for path in expected_resolved):
        raise RuntimeError("Overview projection path escaped its generated directory")

    changed: list[Path] = []
    if output.exists():
        for path in sorted(output.rglob("*.md")):
            resolved = path.resolve()
            if resolved in expected_resolved:
                continue
            if GENERATED_NOTICE not in path.read_text(encoding="utf-8"):
                raise RuntimeError(f"Refusing to delete unmarked projection file: {path}")
            path.unlink()
            changed.append(path)

    for path, content in expected_resolved.items():
        if write_if_changed(path, content):
            changed.append(path)

    if output.exists():
        for directory in sorted((path for path in output.rglob("*") if path.is_dir()), reverse=True):
            try:
                directory.rmdir()
            except OSError:
                pass
    return changed


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(root: Path) -> int:
    canonical = root / CANONICAL_OVERVIEW
    if not canonical.exists():
        print(f"Missing canonical overview: {canonical}", file=sys.stderr)
        return 1
    before = sha256(canonical)
    try:
        sections = split_overview_sections(canonical.read_text(encoding="utf-8"))
        history = collect_update_history(root)
        expected = expected_projection_files(root, sections, history)
        changed = sync_projection_files(root, expected)
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Overview projection failed: {error}", file=sys.stderr)
        return 1
    after = sha256(canonical)
    if before != after:
        print("Overview projection modified the canonical overview", file=sys.stderr)
        return 1
    print(
        f"Overview projections: days={len(history)}, "
        f"updates={sum(len(events) for events in history.values())}, "
        f"open_questions={'present' if sections.open_questions else 'empty'}, "
        f"changed_files={len(changed)}"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    args = parser.parse_args()
    return run(args.root.resolve())


if __name__ == "__main__":
    raise SystemExit(main())
