#!/usr/bin/env python3
"""Prepare content/wiki for Hugo rendering."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from urllib.parse import quote


ROOT = Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "content" / "wiki"
EPISODES_DIR = ROOT / "content" / "episodes"
STATS_PATH = WIKI_DIR / "stats.md"
DATA_PATH = ROOT / "data" / "wiki_links.json"
PUBLIC_SECTIONS = ("concepts", "entities", "sources")
ALPHABETICAL_SECTIONS = ("concepts", "entities")
ALPHABETICAL_BUCKETS = ("#", "0-9", *(chr(code) for code in range(ord("a"), ord("z") + 1)))
# The vendored table keeps Chinese grouping deterministic and dependency-free at
# publish time. Rare CJK characters without a table entry fail closed instead
# of being silently assigned to the symbol bucket.
PINYIN_INITIALS_PATH = ROOT / "scripts" / "data" / "pinyin-initials.txt"
GENERATED_NOTICE = "<!-- Generated by scripts/prepare-wiki-content.py; do not edit manually. -->"
LINK_RE = re.compile(r"\[\[([^\]\n]+)\]\]")


def is_chinese_character(value: str) -> bool:
    return any(
        start <= ord(value) <= end
        for start, end in (
            (0x3400, 0x4DBF),
            (0x4E00, 0x9FFF),
            (0xF900, 0xFAFF),
            (0x20000, 0x2EBEF),
            (0x30000, 0x323AF),
        )
    )


@lru_cache(maxsize=1)
def pinyin_initial_blocks() -> dict[int, str]:
    blocks: dict[int, str] = {}
    for line_number, raw_line in enumerate(
        PINYIN_INITIALS_PATH.read_text(encoding="ascii").splitlines(),
        start=1,
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            start_text, initials = line.split(maxsplit=1)
            start = int(start_text, 16)
        except ValueError as error:
            raise RuntimeError(
                f"Invalid pinyin initials table at line {line_number}"
            ) from error
        if len(initials) > 256 or not re.fullmatch(r"[a-z-]+", initials):
            raise RuntimeError(f"Invalid pinyin initials table at line {line_number}")
        blocks[start] = initials
    return blocks


def chinese_pinyin_initial(value: str) -> str:
    codepoint = ord(value)
    block_start = codepoint & ~0xFF
    initials = pinyin_initial_blocks().get(block_start, "")
    offset = codepoint - block_start
    initial = initials[offset] if offset < len(initials) else "-"
    if initial == "-":
        raise ValueError(f"Unsupported Chinese canonical wiki key: {value!r}")
    return initial


def alphabetical_bucket_slug(bucket: str) -> str:
    return "symbols" if bucket == "#" else bucket


def alphabetical_bucket(key: str) -> str:
    """Return the static #, 0-9, or A-Z bucket for a canonical wiki key."""
    first = key[:1]
    if not first:
        raise ValueError("Canonical wiki key cannot be empty")
    if first.isascii() and first.isdigit():
        return "0-9"
    if first.isascii() and first.isalpha():
        return first.lower()
    if is_chinese_character(first):
        return chinese_pinyin_initial(first)
    return "#"


def wiki_link_target(raw: str) -> str:
    return raw.strip().split("|", 1)[0].strip()


@dataclass(frozen=True)
class WikiPage:
    key: str
    title: str
    section: str
    path: Path

    @property
    def rel_path(self) -> str:
        return self.path.relative_to(ROOT).as_posix()


def group_alphabetical_pages(pages: list[WikiPage], section: str) -> dict[str, list[WikiPage]]:
    groups = {bucket: [] for bucket in ALPHABETICAL_BUCKETS}
    for page in pages:
        if page.section == section:
            groups[alphabetical_bucket(page.key)].append(page)
    for values in groups.values():
        values.sort(key=lambda page: (page.title.casefold(), page.key.casefold()))
    return groups


@dataclass(frozen=True)
class SourceEpisodeReport:
    total_sources: int
    matched: int
    missing_source_file: tuple[Path, ...]
    unmatched_source_file: tuple[tuple[Path, str], ...]

    @property
    def has_errors(self) -> bool:
        return bool(self.missing_source_file or self.unmatched_source_file)


def split_front_matter(text: str) -> tuple[list[str], str]:
    lines = text.splitlines()
    if not lines or lines[0] not in {"---", "+++"}:
        return [], text

    delimiter = lines[0]
    for index, line in enumerate(lines[1:], start=1):
        if line == delimiter:
            body = "\n".join(lines[index + 1 :])
            return lines[1:index], body
    return [], text


def strip_quotes(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def read_front_matter_value(path: Path, key: str) -> str:
    text = path.read_text(encoding="utf-8")
    front_matter, _ = split_front_matter(text)
    yaml_prefix = f"{key}:"
    toml_prefix = f"{key} ="

    for line in front_matter:
        line = line.strip()
        if line.startswith(yaml_prefix):
            return strip_quotes(line.split(":", 1)[1])
        if line.startswith(toml_prefix):
            return strip_quotes(line.split("=", 1)[1])

    return ""


def read_title(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    front_matter, body = split_front_matter(text)

    for line in front_matter:
        if line.startswith("title:"):
            title = strip_quotes(line.split(":", 1)[1])
            if title:
                return title

    heading = re.search(r"(?m)^#\s+(.+?)\s*$", body)
    if heading:
        return heading.group(1)

    return path.stem


def is_canonical_page_path(path: Path) -> bool:
    return path.name != "_index.md"


def discover_pages() -> list[WikiPage]:
    pages: list[WikiPage] = []
    overview = WIKI_DIR / "overview.md"
    if overview.exists():
        pages.append(WikiPage("overview", read_title(overview), "overview", overview))

    for section in PUBLIC_SECTIONS:
        section_dir = WIKI_DIR / section
        if not section_dir.exists():
            continue
        for path in sorted(section_dir.glob("*.md")):
            if not is_canonical_page_path(path):
                continue
            pages.append(WikiPage(path.stem, read_title(path), section, path))

    return pages


def duplicate_keys(pages: list[WikiPage]) -> dict[str, list[WikiPage]]:
    by_key: dict[str, list[WikiPage]] = defaultdict(list)
    for page in pages:
        by_key[page.key].append(page)
    return {key: values for key, values in by_key.items() if len(values) > 1}


def scan_wiki_links(pages_by_key: dict[str, WikiPage]) -> tuple[int, dict[str, list[str]]]:
    missing: dict[str, list[str]] = defaultdict(list)
    total = 0

    for path in sorted(WIKI_DIR.rglob("*.md")):
        if skip_link_scan(path):
            continue
        text = path.read_text(encoding="utf-8")
        rel_path = path.relative_to(ROOT).as_posix()
        for match in LINK_RE.finditer(text):
            total += 1
            target = wiki_link_target(match.group(1))
            if target not in pages_by_key:
                missing[target].append(rel_path)

    return total, dict(sorted(missing.items()))


def section_counts(pages: list[WikiPage]) -> dict[str, int]:
    counts = {"overview": 0, "concepts": 0, "entities": 0, "sources": 0}
    for page in pages:
        counts[page.section] = counts.get(page.section, 0) + 1
    return counts


def scan_source_episodes() -> SourceEpisodeReport:
    source_dir = WIKI_DIR / "sources"
    if not source_dir.exists():
        return SourceEpisodeReport(0, 0, (), ())

    episode_names = {
        path.name
        for path in sorted(EPISODES_DIR.glob("*.md"))
        if not path.name.startswith("_")
    }
    missing_source_file: list[Path] = []
    unmatched_source_file: list[tuple[Path, str]] = []
    matched = 0
    total_sources = 0

    for path in sorted(source_dir.glob("*.md")):
        if path.name.startswith("_"):
            continue
        total_sources += 1
        source_file = read_front_matter_value(path, "source_file")
        if not source_file:
            missing_source_file.append(path)
            continue

        source_name = Path(source_file).name
        if source_name in episode_names:
            matched += 1
        else:
            unmatched_source_file.append((path, source_name))

    return SourceEpisodeReport(
        total_sources=total_sources,
        matched=matched,
        missing_source_file=tuple(missing_source_file),
        unmatched_source_file=tuple(unmatched_source_file),
    )


def generated_index(title: str, description: str, cascade_outputs: bool = False) -> str:
    lines = [
        "---",
        f'title: "{title}"',
        'type: "wiki"',
        f'description: "{description}"',
        'outputs: ["html"]',
    ]
    if cascade_outputs:
        lines.extend(
            [
                "cascade:",
                '  outputs: ["html"]',
            ]
        )
    lines.extend(
        [
            "---",
            "",
            GENERATED_NOTICE,
        ]
    )
    return "\n".join(lines) + "\n"


def alphabetical_index(
    section: str,
    bucket: str,
    pages: list[WikiPage],
    total_pages: int,
    *,
    section_landing: bool = False,
) -> str:
    section_title = section.title()
    bucket_title = bucket.upper()
    title = section_title if section_landing else f"{section_title} — {bucket_title}"
    lines = [
        "---",
        f"title: {json.dumps(title, ensure_ascii=False)}",
        'type: "wiki"',
        f"description: {json.dumps(f'{section_title} beginning with {bucket_title}', ensure_ascii=False)}",
        'outputs: ["html"]',
        "wiki_alphabetical: true",
        f"wiki_section: {json.dumps(section)}",
        f"wiki_letter: {json.dumps(bucket)}",
        f"wiki_total_pages: {total_pages}",
    ]
    if pages:
        lines.append("wiki_pages:")
    else:
        lines.append("wiki_pages: []")
    for page in pages:
        lines.extend(
            [
                f"  - key: {json.dumps(page.key, ensure_ascii=False)}",
                f"    title: {json.dumps(page.title, ensure_ascii=False)}",
                f"    url: {json.dumps(page_url(page), ensure_ascii=False)}",
            ]
        )
    lines.extend(["---", "", GENERATED_NOTICE])
    return "\n".join(lines) + "\n"


def expected_alphabetical_files(pages: list[WikiPage]) -> dict[Path, str]:
    generated: dict[Path, str] = {}
    for section in ALPHABETICAL_SECTIONS:
        groups = group_alphabetical_pages(pages, section)
        total_pages = sum(len(values) for values in groups.values())
        section_dir = WIKI_DIR / section
        default_content = alphabetical_index(
            section,
            "a",
            groups["a"],
            total_pages,
            section_landing=True,
        )
        generated[section_dir / "_index.md"] = default_content
        generated[section_dir / "by-letter" / "_index.md"] = alphabetical_index(
            section,
            "a",
            groups["a"],
            total_pages,
        )
        for bucket in ALPHABETICAL_BUCKETS:
            generated[
                section_dir / "by-letter" / alphabetical_bucket_slug(bucket) / "_index.md"
            ] = alphabetical_index(
                section,
                bucket,
                groups[bucket],
                total_pages,
            )
    return generated


def needs_safe_page_proxy(page: WikiPage) -> bool:
    """Use a stable route because Hugo normalizes symbol-leading filenames."""
    return alphabetical_bucket(page.key) == "#"


def safe_page_slug(key: str) -> str:
    hint = re.sub(r"[^a-z0-9]+", "-", key.lower()).strip("-")[:32] or "entry"
    digest = hashlib.sha256(key.encode("utf-8")).hexdigest()
    return f"{hint}-{digest}"


def expected_safe_page_files(pages: list[WikiPage]) -> dict[Path, str]:
    generated: dict[Path, str] = {}
    for page in pages:
        if not needs_safe_page_proxy(page):
            continue
        path = WIKI_DIR / page.section / "by-key" / safe_page_slug(page.key) / "index.md"
        if path in generated:
            raise ValueError(f"safe route collision for {page.section}/{page.key}: {path}")
        content = page.path.read_text(encoding="utf-8").rstrip()
        generated[path] = f"{content}\n\n{GENERATED_NOTICE}\n"
    return generated


def find_stale_safe_page_files(
    expected_paths: set[Path],
    *,
    wiki_dir: Path = WIKI_DIR,
) -> list[Path]:
    stale: list[Path] = []
    for path in sorted(wiki_dir.glob("*/by-key/*/index.md")):
        if path in expected_paths:
            continue
        if GENERATED_NOTICE in path.read_text(encoding="utf-8"):
            stale.append(path)
    return stale


def expected_generated_files() -> dict[Path, str]:
    pages = discover_pages()
    return {
        WIKI_DIR / "_index.md": generated_index(
            "Wiki",
            "Podcast Atlas wiki",
            cascade_outputs=True,
        ),
        WIKI_DIR / "sources" / "_index.md": generated_index(
            "Sources",
            "Source pages in the Podcast Atlas wiki",
        ),
        DATA_PATH: make_link_data(pages),
        **expected_alphabetical_files(pages),
        **expected_safe_page_files(pages),
    }


def page_url(page: WikiPage) -> str:
    if page.section == "overview":
        return "/wiki/overview/"
    if needs_safe_page_proxy(page):
        return f"/wiki/{page.section}/by-key/{safe_page_slug(page.key)}/"
    return f"/wiki/{page.section}/{quote(page.key.lower(), safe='')}/"


def make_link_data(pages: list[WikiPage]) -> str:
    data = {
        page.key: {
            "title": page.title,
            "url": page_url(page),
        }
        for page in sorted(pages, key=lambda item: item.key)
    }
    return json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def make_stats_page(
    pages: list[WikiPage],
    total_links: int,
    missing: dict[str, list[str]],
    duplicates: dict[str, list[WikiPage]],
    source_episode_report: SourceEpisodeReport,
) -> str:
    counts = section_counts(pages)
    unique_targets = total_unique_link_targets()
    lines = [
        "---",
        'title: "Wiki Stats"',
        "type: stats",
        'description: "Podcast Atlas wiki statistics"',
        'outputs: ["html"]',
        "---",
        "",
        f"{GENERATED_NOTICE}",
        "",
        "# Wiki Stats",
        "",
        "## Pages",
        f"- Overview: {counts.get('overview', 0)}",
        f"- Concepts: {counts.get('concepts', 0)}",
        f"- Entities: {counts.get('entities', 0)}",
        f"- Sources: {counts.get('sources', 0)}",
        f"- Total wiki content pages: {len(pages)}",
        "",
        "## Links",
        f"- Wiki link references: {total_links}",
        f"- Unique wiki link targets: {unique_targets}",
        f"- Missing targets: {len(missing)}",
        f"- Duplicate file-name targets: {len(duplicates)}",
        "",
        "## Source Episodes",
        f"- Source pages: {source_episode_report.total_sources}",
        f"- Matched episodes: {source_episode_report.matched}",
        f"- Missing source_file: {len(source_episode_report.missing_source_file)}",
        f"- Unmatched source_file: {len(source_episode_report.unmatched_source_file)}",
        "",
    ]

    if duplicates:
        lines.extend(["## Duplicate Targets", ""])
        for key, values in sorted(duplicates.items()):
            lines.append(f"- `{key}`")
            for page in values:
                lines.append(f"  - `{page.rel_path}`")
        lines.append("")

    if missing:
        lines.extend(["## Missing Targets", ""])
        for target, referrers in missing.items():
            lines.append(f"- `[[{target}]]`")
            for referrer in sorted(set(referrers)):
                lines.append(f"  - `{referrer}`")
        lines.append("")

    if source_episode_report.missing_source_file:
        lines.extend(["## Missing Source File Metadata", ""])
        for path in source_episode_report.missing_source_file:
            lines.append(f"- `{path.relative_to(ROOT).as_posix()}`")
        lines.append("")

    if source_episode_report.unmatched_source_file:
        lines.extend(["## Unmatched Source Episodes", ""])
        for path, source_name in source_episode_report.unmatched_source_file:
            lines.append(f"- `{path.relative_to(ROOT).as_posix()}` -> `{source_name}`")
        lines.append("")

    if not duplicates and not missing:
        lines.append("All wiki links resolve to public wiki pages.")
        lines.append("")

    if not source_episode_report.has_errors:
        lines.append("All wiki source pages resolve to episode pages.")
        lines.append("")

    return "\n".join(lines)


def total_unique_link_targets() -> int:
    targets: set[str] = set()
    for path in sorted(WIKI_DIR.rglob("*.md")):
        if skip_link_scan(path):
            continue
        text = path.read_text(encoding="utf-8")
        targets.update(wiki_link_target(match.group(1)) for match in LINK_RE.finditer(text))
    return len(targets)


def skip_link_scan(path: Path) -> bool:
    try:
        relative = path.relative_to(WIKI_DIR)
    except ValueError:
        relative = None
    is_safe_proxy = (
        relative is not None
        and len(relative.parts) == 4
        and relative.parts[1] == "by-key"
        and relative.parts[3] == "index.md"
    )
    return path.name == "_index.md" or path == STATS_PATH or is_safe_proxy


def compare_file(path: Path, expected: str) -> bool:
    return path.exists() and path.read_text(encoding="utf-8") == expected


def write_if_changed(path: Path, expected: str) -> bool:
    if compare_file(path, expected):
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8")
    return True


def run(check: bool) -> int:
    if not WIKI_DIR.exists():
        print(f"Missing wiki directory: {WIKI_DIR.relative_to(ROOT)}", file=sys.stderr)
        return 1

    pages = discover_pages()
    duplicates = duplicate_keys(pages)
    pages_by_key = {page.key: page for page in pages}
    total_links, missing = scan_wiki_links(pages_by_key)
    source_episode_report = scan_source_episodes()
    generated_files = expected_generated_files()
    stats_page = make_stats_page(pages, total_links, missing, duplicates, source_episode_report)
    expected = {**generated_files, STATS_PATH: stats_page}
    stale_safe_pages = find_stale_safe_page_files(set(expected))

    changed: list[str] = []
    if check:
        for path, content in expected.items():
            if not compare_file(path, content):
                changed.append(path.relative_to(ROOT).as_posix())
        changed.extend(path.relative_to(ROOT).as_posix() for path in stale_safe_pages)
    else:
        for path, content in expected.items():
            if write_if_changed(path, content):
                changed.append(path.relative_to(ROOT).as_posix())
        for path in stale_safe_pages:
            path.unlink()
            changed.append(path.relative_to(ROOT).as_posix())
            for directory in (path.parent, path.parent.parent):
                try:
                    directory.rmdir()
                except OSError:
                    break

    counts = section_counts(pages)
    print(
        "Wiki pages: "
        f"overview={counts.get('overview', 0)}, "
        f"concepts={counts.get('concepts', 0)}, "
        f"entities={counts.get('entities', 0)}, "
        f"sources={counts.get('sources', 0)}"
    )
    print(f"Wiki links: references={total_links}, unique_targets={total_unique_link_targets()}")
    print(
        "Source episodes: "
        f"sources={source_episode_report.total_sources}, "
        f"matched={source_episode_report.matched}, "
        f"missing_source_file={len(source_episode_report.missing_source_file)}, "
        f"unmatched_source_file={len(source_episode_report.unmatched_source_file)}"
    )

    errors = bool(duplicates or missing or source_episode_report.has_errors)
    if duplicates:
        print(f"Duplicate wiki targets: {len(duplicates)}", file=sys.stderr)
    if missing:
        print(f"Missing wiki targets: {len(missing)}", file=sys.stderr)
    if source_episode_report.missing_source_file:
        print(
            f"Wiki source pages missing source_file: {len(source_episode_report.missing_source_file)}",
            file=sys.stderr,
        )
    if source_episode_report.unmatched_source_file:
        print(
            f"Wiki source pages with unmatched source_file: {len(source_episode_report.unmatched_source_file)}",
            file=sys.stderr,
        )

    if check:
        if changed:
            print("Out-of-date generated files:", file=sys.stderr)
            for path in changed:
                print(f"  {path}", file=sys.stderr)
        elif not errors:
            print("Wiki generated files are up to date.")
    else:
        if changed:
            print("Updated:")
            for path in changed:
                print(f"  {path}")
        else:
            print("No generated file changes.")

    return 1 if errors or changed and check else 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare content/wiki for Hugo.")
    parser.add_argument("--check", action="store_true", help="check generated files without writing")
    args = parser.parse_args()
    return run(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
